theme: jekyll-theme-minimal

title: Automatic Door Control 
description: The homepage for the Automatic Door Control Project featuring project updates and more.

email: automaticdoorcontrol@gmail.com
twitter_username: autodoorcontrol

markdown: kramdown
