theme: jekyll-theme-minimal

title: Automatic Door Control 
description: The homepage for the Automatic Door Control Project featuring project updates and more.

salesteams:
-title: Features
subfolderitems:
  -feature voiceover

email: automaticdoorcontrol@gmail.com
twitter_username: autodoorcontrol


sass:
  sass_dir: _sass
include: ['_pages']

markdown: kramdown
